workflows:
  build:
    name: Build and Test
    environment:
      flutter: stable
      node: latest
      xcode: latest
     

    scripts:
      - name: Install Dependencies
        script: |
          yarn install

      - name: Run Tests
        script: |
          yarn test

      - name: Build Android
        script: |
          cd android && ./gradlew assembleRelease

      - name: Build iOS
        script: |
          cd ios && xcodebuild -workspace YourProject.xcworkspace -scheme YourScheme -configuration Release -archivePath build/YourProject.xcarchive archive

    artifacts:
      - build/outputs/apk/release/*.apk
      - ios/build/*.app
